### ISSUE TITLE
[FEATURE] Add Release date of Movies 

### ISSUE THREAD

**Issue by kabir0x23** [kabir0x23/MovieLand#25]
### Detailed description

Add the release year below the movie name.

![image](https://user-images.githubusercontent.com/44284877/193046706-33478fc2-e9ff-4361-9f05-67750a0a649a.png)

### Context

We are using API for fetching movies.
If you need any kind of help let us know.

### Additional information

if you have any questions or doubts, feel free to ask below. 👇

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codewithnadeem14502** [comment]
hello sir/mam , i want to work on this issue , can you explain me what should i do , i am completely new to open source , hope you relpy me thank you

**Comment by kabir0x23** [comment]
> hello sir/mam , i want to work on this issue , can you explain me what should i do , i am completely new to open source , hope you reply me thank you

Will you checkout this repository frist?
https://github.com/CryptoverseWeb3/git-github-practice

**Comment by kabir0x23** [comment]
> hello sir/mam , i want to work on this issue , can you explain me what should i do , i am completely new to open source , hope you relpy me thank you

When you open that website,you got movies

We have to mention release date side of movies name

We are fetching all the movies with apis

**Comment by kabir0x23** [comment]
> hello sir/mam , i want to work on this issue , can you explain me what should i do , i am completely new to open source , hope you relpy me thank you

Have you worked APIs before?

**Comment by najeebkp** [comment]
Hi, I understood that we need to show the release date along with the movie name. I would like to contribute for this particular issue. Can you please assign me?

**Comment by kabir0x23** [comment]
> Hi, I understood that we need to show the release date along with the movie name. I would like to contribute for this particular issue. Can you please assign me? @kabir0x23 
> I'm excited for my first ever opensource contribution !

That's great, I am assigning you this particular issue.

If you need more green squares
Then 

Will you checkout this repository frist?
https://github.com/CryptoverseWeb3/git-github-practice

+ You will get more green squares

**Comment by najeebkp** [comment]
Sure. I'll follow the same. Thanks

**Comment by kabir0x23** [comment]
> Sure. I'll follow the same. Thanks

assigned @najeebkp

**Comment by najeebkp** [comment]
Thank you.

**Comment by kabir0x23** [comment]
> Sure. I'll follow the same. Thanks

i have uploaded the reference image, you can check it out.
![image](https://user-images.githubusercontent.com/44284877/193046951-ce7572c3-66cd-433a-a3c0-0b37368d653c.png)
