### ISSUE TITLE
[FEATURE] Sidebar

### ISSUE THREAD

**Issue by kabir0x23** [kabir0x23/MovieLand#30]
### Detailed description

![image](https://user-images.githubusercontent.com/44284877/193395076-35b0828a-7778-450a-910f-ebe62a15626f.png)
example website: https://filmpire.netlify.app/

our website example:
website: https://movieapp-docker.herokuapp.com/
![image](https://user-images.githubusercontent.com/44284877/193395170-3ba2467f-8328-4d08-ae2a-6d622b3ffbd4.png)

### Context

We want to build this sidebar:
- we want to add Categories on the left side
- example
![image](https://user-images.githubusercontent.com/44284877/193395120-48ab8021-0717-44f9-b0f9-1205de6781b0.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codewithnadeem14502** [comment]
sir, can i contribute to this , can you assign me this

**Comment by hs-07** [comment]
hey @kabir0x23 ,
I had gone the issue mentioned below and thought of working over it  with full energy🙌. I am pretty comfortable working on such kind of stuff 😊 and worked a lot in past.
I understood the design you mentioned below and will try my best to give better results than that.


> ### Detailed description
> ![image](https://user-images.githubusercontent.com/44284877/193395076-35b0828a-7778-450a-910f-ebe62a15626f.png) example website: https://filmpire.netlify.app/
> 
> our website example: website: https://movieapp-docker.herokuapp.com/ ![image](https://user-images.githubusercontent.com/44284877/193395170-3ba2467f-8328-4d08-ae2a-6d622b3ffbd4.png)
> 
> ### Context
> We want to build this sidebar:
> 
> * we want to add Categories on the left side
> * example
>   ![image](https://user-images.githubusercontent.com/44284877/193395120-48ab8021-0717-44f9-b0f9-1205de6781b0.png)

Please mention what all categories you want me to put on the site.
I had prepared it on my localhost, just Assign me the task so that i could start working overit.

Thankyou.

**Comment by kabir0x23** [comment]
Hey @hs-07 
Will you contribute to this repo first.
- https://github.com/cryptoverseWeb3/git-github-practice

I will assign you this issue

**Comment by hs-07** [comment]
@kabir0x23 
I had contributed in it.

**Comment by kabir0x23** [comment]
> @kabir0x23 I had contributed in it.

Nice, and assigned

**Comment by hs-07** [comment]
@kabir0x23 
i wanna ask that you need a static sidebar or a dynamic one like I attached ss below???
![Screenshot (6)](https://user-images.githubusercontent.com/87127387/193444710-b7b7b9e2-734d-4410-9701-e6c079cc7f80.png)
![Screenshot 2022-10-02 134413](https://user-images.githubusercontent.com/87127387/193444712-1ee64847-5e88-466e-bd80-e43aebcbb768.png)

**Comment by kabir0x23** [comment]
> @kabir0x23 i wanna ask that you need a static sidebar or a dynamic one like I attached ss below??? ![Screenshot (6)](https://user-images.githubusercontent.com/87127387/193444710-b7b7b9e2-734d-4410-9701-e6c079cc7f80.png) ![Screenshot 2022-10-02 134413](https://user-images.githubusercontent.com/87127387/193444712-1ee64847-5e88-466e-bd80-e43aebcbb768.png)

Like if you know how to use APIs, then dynamic
Otherwise static will be okay

**Comment by kabir0x23** [comment]
hello @hs-07 
any progreess?

If you need any help or have any doubts or questions let us know.

Thank you 😄.

**Comment by hs-07** [comment]
@kabir0x23 
yaa sure..
I had almost done it ....but while integrating , some error is coming. Will resolve it soon.

**Comment by kabir0x23** [comment]
> @kabir0x23 yaa sure.. I had almost done it ....but while integrating , some error is coming. Will resolve it soon.

Awesome. 😄
