### ISSUE TITLE
[FEATURE] Improve date design

### ISSUE THREAD

**Issue by kabir0x23** [kabir0x23/MovieLand#35]
### Detailed description

![image](https://user-images.githubusercontent.com/44284877/195856649-8af3021b-27ab-4dfe-9a38-a1dad0601f2a.png)

### Context

Improve date design

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sumit-022** [comment]
I can work on this. Please assign me this issue

**Comment by DarkSoul26** [comment]
@kabir0x23 I would like to work on this issue

**Comment by kabir0x23** [comment]
@sumit-022 @DarkSoul26 

I didn;t notice your message before.

PLease checkout this issue.
#37

**Comment by kabir0x23** [comment]
If you need more good projects, let me know,.
