### ISSUE TITLE
[OTHER] change the cursor in toggle-darkmode btn

### ISSUE THREAD

**Issue by pantbibek21** [kabir0x23/MovieLand#40]
### What would you like to share?

Hello sir, I saw that the toggle mode button was having the default cursor. It would be more intuitive for new people if we had the pointer cursor. 

### Additional information

A pointer cursor could provide better UX, just what I felt. I am new to open source and if you find the issue is okay, let me change that sir.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
Great, I am assigning this issue to you.

**Comment by kabir0x23** [comment]
#43
