### ISSUE TITLE
[FEATURE] Adding Footer to the website

### ISSUE THREAD

**Issue by Kritika30032002** [kabir0x23/MovieLand#41]
### Detailed description

Adding Footer to the website which include
-copyright line
-social icons with hover effect and links to them if got available.

### Context

To give more information about the owner of the website and their social media links.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kritika30032002** [comment]
Assign this to me!!

**Comment by kabir0x23** [comment]
Great, I am assigning this issue to you.

**Comment by Yashpsct010** [comment]
please assign this to me.

**Comment by kabir0x23** [comment]
Hey @Yashpsct010  
This issue already has been assigned to @Kritika30032002.

You can check other issues.

**Comment by Yashpsct010** [comment]
You can assign multiple people a single task and it is upto you to merge pr or both please

**Comment by kabir0x23** [comment]
> You can
> 
> Well atleast assign me

already assigned, if you both are going to send the same pr, we will get conflicts 
github dosenot work like this,

**Comment by Kritika30032002** [comment]
I am working on it @kabir0x23

**Comment by Yashpsct010** [comment]
https://github.blog/2016-05-27-multiple-assignees-on-issues-and-pull-requests/

**Comment by kabir0x23** [comment]
> https://github.blog/2016-05-27-multiple-assignees-on-issues-and-pull-requests/

i am well aware of that , we can assign 10 members on the same issue, only if they want to contributing in the same issue, by dividing there tasks.
- like one is working on some part of the issue and some on other

This is the very small issue, one person is enough
