### ISSUE TITLE
[FEATURE] Adding Scroll to top Button feature

### ISSUE THREAD

**Issue by Kritika30032002** [kabir0x23/MovieLand#42]
### Detailed description

Adding Scroll to top Button feature

It will scroll the website to the top.

Assign this to me.

### Context

After Scrolling down too much , it will make easier to go to the top without again scrolling that much.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
Great, I am assigning this issue to you.

**Comment by Yashpsct010** [comment]
please assign this to me

**Comment by kabir0x23** [comment]
> please assign this to me

Can you share your tech-stack so i can provide issues related to it

**Comment by Kritika30032002** [comment]
@kabir0x23 I can only submit PR for this issue when my already submitted PR gets merged otherwise all the commits will be done in the same PR.

So kindly review My already submitted PR @kabir0x23

**Comment by kabir0x23** [comment]
> @kabir0x23 I can only submit PR for this issue when my already submitted PR gets merged otherwise all the commits will be done in the same PR.
> 
> So kindly review My already submitted PR @kabir0x23

done

**Comment by Kritika30032002** [comment]
> > @kabir0x23 I can only submit PR for this issue when my already submitted PR gets merged otherwise all the commits will be done in the same PR.
> > So kindly review My already submitted PR @kabir0x23
> 
> done

Okay

PR for this issue will be submitted by today

**Comment by kabir0x23** [comment]
> > > @kabir0x23 I can only submit PR for this issue when my already submitted PR gets merged otherwise all the commits will be done in the same PR.
> > > So kindly review My already submitted PR @kabir0x23
> > 
> > 
> > done
> 
> Okay
> 
> PR for this issue will be submitted by today

Greate 💪🏽
